# Generated by Django 2.2.16 on 2023-01-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_profile_picture.jpg', upload_to='profile_pics'),
        ),
    ]
