# Generated by Django 2.2.16 on 2023-01-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230126_0007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
